// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compiler int32

const (
	Compiler_PROTO  Compiler = 0
	Compiler_JSON   Compiler = 1
	Compiler_JSONPB Compiler = 2
)

// Enum value maps for Compiler.
var (
	Compiler_name = map[int32]string{
		0: "PROTO",
		1: "JSON",
		2: "JSONPB",
	}
	Compiler_value = map[string]int32{
		"PROTO":  0,
		"JSON":   1,
		"JSONPB": 2,
	}
)

func (x Compiler) Enum() *Compiler {
	p := new(Compiler)
	*p = x
	return p
}

func (x Compiler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compiler) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[0].Descriptor()
}

func (Compiler) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[0]
}

func (x Compiler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compiler.Descriptor instead.
func (Compiler) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

type ApiType int32

const (
	ApiType_Send  ApiType = 0 // 单传入参数
	ApiType_Call  ApiType = 1 // 单传入参数，单传出参数解析
	ApiType_Multi ApiType = 2 // 多参数传入，单参数传出解析
)

// Enum value maps for ApiType.
var (
	ApiType_name = map[int32]string{
		0: "Send",
		1: "Call",
		2: "Multi",
	}
	ApiType_value = map[string]int32{
		"Send":  0,
		"Call":  1,
		"Multi": 2,
	}
)

func (x ApiType) Enum() *ApiType {
	p := new(ApiType)
	*p = x
	return p
}

func (x ApiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_proto_enumTypes[1].Descriptor()
}

func (ApiType) Type() protoreflect.EnumType {
	return &file_node_proto_enumTypes[1]
}

func (x ApiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiType.Descriptor instead.
func (ApiType) EnumDescriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// process ID
	Pid uint64 `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	// server version
	Ver string `protobuf:"bytes,2,opt,name=Ver,proto3" json:"Ver,omitempty"`
	// server node uuid
	Uuid string `protobuf:"bytes,3,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	// server node name
	Name string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	// main node
	Main bool `protobuf:"varint,5,opt,name=Main,proto3" json:"Main,omitempty"`
	// localhost address
	Host string `protobuf:"bytes,6,opt,name=Host,proto3" json:"Host,omitempty"`
	// tcp local listen port
	Tport uint64 `protobuf:"varint,7,opt,name=Tport,proto3" json:"Tport,omitempty"`
	// udp local listen port
	Uport uint64 `protobuf:"varint,8,opt,name=Uport,proto3" json:"Uport,omitempty"`
	// http local listen port
	Hport uint64 `protobuf:"varint,9,opt,name=Hport,proto3" json:"Hport,omitempty"`
	// local api types: send or call, protocal
	Funcs []*FuncApi `protobuf:"bytes,10,rep,name=Funcs,proto3" json:"Funcs,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NodeInfo) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *NodeInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetMain() bool {
	if x != nil {
		return x.Main
	}
	return false
}

func (x *NodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeInfo) GetTport() uint64 {
	if x != nil {
		return x.Tport
	}
	return 0
}

func (x *NodeInfo) GetUport() uint64 {
	if x != nil {
		return x.Uport
	}
	return 0
}

func (x *NodeInfo) GetHport() uint64 {
	if x != nil {
		return x.Hport
	}
	return 0
}

func (x *NodeInfo) GetFuncs() []*FuncApi {
	if x != nil {
		return x.Funcs
	}
	return nil
}

type FuncApi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type ApiType  `protobuf:"varint,5,opt,name=Type,proto3,enum=ApiType" json:"Type,omitempty"`
	Kind Compiler `protobuf:"varint,6,opt,name=Kind,proto3,enum=Compiler" json:"Kind,omitempty"`
}

func (x *FuncApi) Reset() {
	*x = FuncApi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncApi) ProtoMessage() {}

func (x *FuncApi) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncApi.ProtoReflect.Descriptor instead.
func (*FuncApi) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *FuncApi) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FuncApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FuncApi) GetType() ApiType {
	if x != nil {
		return x.Type
	}
	return ApiType_Send
}

func (x *FuncApi) GetKind() Compiler {
	if x != nil {
		return x.Kind
	}
	return Compiler_PROTO
}

type FuncMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncID   uint32   `protobuf:"varint,1,opt,name=FuncID,proto3" json:"FuncID,omitempty"`
	ApiName  string   `protobuf:"bytes,2,opt,name=ApiName,proto3" json:"ApiName,omitempty"`
	ServName string   `protobuf:"bytes,3,opt,name=ServName,proto3" json:"ServName,omitempty"`
	FuncName string   `protobuf:"bytes,4,opt,name=FuncName,proto3" json:"FuncName,omitempty"`
	ApiType  ApiType  `protobuf:"varint,5,opt,name=ApiType,proto3,enum=ApiType" json:"ApiType,omitempty"`
	Protocal Compiler `protobuf:"varint,6,opt,name=Protocal,proto3,enum=Compiler" json:"Protocal,omitempty"`
}

func (x *FuncMsg) Reset() {
	*x = FuncMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuncMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuncMsg) ProtoMessage() {}

func (x *FuncMsg) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuncMsg.ProtoReflect.Descriptor instead.
func (*FuncMsg) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *FuncMsg) GetFuncID() uint32 {
	if x != nil {
		return x.FuncID
	}
	return 0
}

func (x *FuncMsg) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *FuncMsg) GetServName() string {
	if x != nil {
		return x.ServName
	}
	return ""
}

func (x *FuncMsg) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *FuncMsg) GetApiType() ApiType {
	if x != nil {
		return x.ApiType
	}
	return ApiType_Send
}

func (x *FuncMsg) GetProtocal() Compiler {
	if x != nil {
		return x.Protocal
	}
	return Compiler_PROTO
}

type UpFuncList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*FuncMsg `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UpFuncList) Reset() {
	*x = UpFuncList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpFuncList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpFuncList) ProtoMessage() {}

func (x *UpFuncList) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpFuncList.ProtoReflect.Descriptor instead.
func (*UpFuncList) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *UpFuncList) GetData() []*FuncMsg {
	if x != nil {
		return x.Data
	}
	return nil
}

type MultiBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32   `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Data  [][]byte `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MultiBody) Reset() {
	*x = MultiBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiBody) ProtoMessage() {}

func (x *MultiBody) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiBody.ProtoReflect.Descriptor instead.
func (*MultiBody) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *MultiBody) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MultiBody) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

var file_node_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x01, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x56,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x54, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x55, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x48, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x48, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1e, 0x0a, 0x05, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x41, 0x70, 0x69, 0x52, 0x05, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x22,
	0x6a, 0x0a, 0x07, 0x46, 0x75, 0x6e, 0x63, 0x41, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x41,
	0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0xbe, 0x01, 0x0a, 0x07,
	0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x75, 0x6e, 0x63, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x46, 0x75, 0x6e, 0x63, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72,
	0x76, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72,
	0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x41, 0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x41, 0x70,
	0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x72, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x61, 0x6c, 0x22, 0x2a, 0x0a, 0x0a,
	0x55, 0x70, 0x46, 0x75, 0x6e, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x4d,
	0x73, 0x67, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x2a,
	0x2b, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x4a, 0x53, 0x4f, 0x4e, 0x50, 0x42, 0x10, 0x02, 0x2a, 0x28, 0x0a, 0x07,
	0x41, 0x70, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData = file_node_proto_rawDesc
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_proto_rawDescData)
	})
	return file_node_proto_rawDescData
}

var file_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_node_proto_goTypes = []interface{}{
	(Compiler)(0),      // 0: Compiler
	(ApiType)(0),       // 1: ApiType
	(*NodeInfo)(nil),   // 2: NodeInfo
	(*FuncApi)(nil),    // 3: FuncApi
	(*FuncMsg)(nil),    // 4: FuncMsg
	(*UpFuncList)(nil), // 5: UpFuncList
	(*MultiBody)(nil),  // 6: MultiBody
}
var file_node_proto_depIdxs = []int32{
	3, // 0: NodeInfo.Funcs:type_name -> FuncApi
	1, // 1: FuncApi.Type:type_name -> ApiType
	0, // 2: FuncApi.Kind:type_name -> Compiler
	1, // 3: FuncMsg.ApiType:type_name -> ApiType
	0, // 4: FuncMsg.Protocal:type_name -> Compiler
	4, // 5: UpFuncList.Data:type_name -> FuncMsg
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncApi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuncMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpFuncList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		EnumInfos:         file_node_proto_enumTypes,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_rawDesc = nil
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
