// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: watch.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	CpuRate uint64 `protobuf:"varint,2,opt,name=CpuRate,proto3" json:"CpuRate,omitempty"`
	MemFree uint64 `protobuf:"varint,3,opt,name=MemFree,proto3" json:"MemFree,omitempty"`
	MemUsed uint64 `protobuf:"varint,4,opt,name=MemUsed,proto3" json:"MemUsed,omitempty"`
	ConnNum uint64 `protobuf:"varint,5,opt,name=ConnNum,proto3" json:"ConnNum,omitempty"`
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{0}
}

func (x *SystemStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SystemStatus) GetCpuRate() uint64 {
	if x != nil {
		return x.CpuRate
	}
	return 0
}

func (x *SystemStatus) GetMemFree() uint64 {
	if x != nil {
		return x.MemFree
	}
	return 0
}

func (x *SystemStatus) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemStatus) GetConnNum() uint64 {
	if x != nil {
		return x.ConnNum
	}
	return 0
}

type SendAllRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SendRsp `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	Count  uint32     `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *SendAllRsp) Reset() {
	*x = SendAllRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAllRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAllRsp) ProtoMessage() {}

func (x *SendAllRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAllRsp.ProtoReflect.Descriptor instead.
func (*SendAllRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{1}
}

func (x *SendAllRsp) GetResult() []*SendRsp {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SendAllRsp) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Network string `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	Success bool   `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SendRsp) Reset() {
	*x = SendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRsp) ProtoMessage() {}

func (x *SendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRsp.ProtoReflect.Descriptor instead.
func (*SendRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{2}
}

func (x *SendRsp) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SendRsp) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SendRsp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisteredRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watch []*NodeInfo `protobuf:"bytes,1,rep,name=Watch,proto3" json:"Watch,omitempty"`
	Funcs []*FuncApi  `protobuf:"bytes,2,rep,name=Funcs,proto3" json:"Funcs,omitempty"`
}

func (x *RegisteredRsp) Reset() {
	*x = RegisteredRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredRsp) ProtoMessage() {}

func (x *RegisteredRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredRsp.ProtoReflect.Descriptor instead.
func (*RegisteredRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{3}
}

func (x *RegisteredRsp) GetWatch() []*NodeInfo {
	if x != nil {
		return x.Watch
	}
	return nil
}

func (x *RegisteredRsp) GetFuncs() []*FuncApi {
	if x != nil {
		return x.Funcs
	}
	return nil
}

// Query function message
type GetFuncMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncID  uint32 `protobuf:"varint,1,opt,name=FuncID,proto3" json:"FuncID,omitempty"`
	ApiName string `protobuf:"bytes,2,opt,name=ApiName,proto3" json:"ApiName,omitempty"`
}

func (x *GetFuncMsgReq) Reset() {
	*x = GetFuncMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuncMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuncMsgReq) ProtoMessage() {}

func (x *GetFuncMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuncMsgReq.ProtoReflect.Descriptor instead.
func (*GetFuncMsgReq) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{4}
}

func (x *GetFuncMsgReq) GetFuncID() uint32 {
	if x != nil {
		return x.FuncID
	}
	return 0
}

func (x *GetFuncMsgReq) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

type GetFuncMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Func *FuncApi   `protobuf:"bytes,1,opt,name=Func,proto3" json:"Func,omitempty"` // request not null
	List []*FuncApi `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"` // request was null, query all
}

func (x *GetFuncMsgRsp) Reset() {
	*x = GetFuncMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuncMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuncMsgRsp) ProtoMessage() {}

func (x *GetFuncMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuncMsgRsp.ProtoReflect.Descriptor instead.
func (*GetFuncMsgRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{5}
}

func (x *GetFuncMsgRsp) GetFunc() *FuncApi {
	if x != nil {
		return x.Func
	}
	return nil
}

func (x *GetFuncMsgRsp) GetList() []*FuncApi {
	if x != nil {
		return x.List
	}
	return nil
}

// Query same node message
type GetNodeMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetNodeMsgReq) Reset() {
	*x = GetNodeMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeMsgReq) ProtoMessage() {}

func (x *GetNodeMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeMsgReq.ProtoReflect.Descriptor instead.
func (*GetNodeMsgReq) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeMsgReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetNodeMsgReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNodeMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *NodeInfo   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"` // use uuid query
	List []*NodeInfo `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"` // use name query
}

func (x *GetNodeMsgRsp) Reset() {
	*x = GetNodeMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeMsgRsp) ProtoMessage() {}

func (x *GetNodeMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeMsgRsp.ProtoReflect.Descriptor instead.
func (*GetNodeMsgRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeMsgRsp) GetData() *NodeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetNodeMsgRsp) GetList() []*NodeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// Query function node to connection call
type GetApiConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncID  uint32 `protobuf:"varint,1,opt,name=FuncID,proto3" json:"FuncID,omitempty"`  // function id
	ApiName string `protobuf:"bytes,2,opt,name=ApiName,proto3" json:"ApiName,omitempty"` // server struct name
}

func (x *GetApiConnReq) Reset() {
	*x = GetApiConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiConnReq) ProtoMessage() {}

func (x *GetApiConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiConnReq.ProtoReflect.Descriptor instead.
func (*GetApiConnReq) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{8}
}

func (x *GetApiConnReq) GetFuncID() uint32 {
	if x != nil {
		return x.FuncID
	}
	return 0
}

func (x *GetApiConnReq) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

type GetApiConnRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Func *FuncMsg    `protobuf:"bytes,1,opt,name=Func,proto3" json:"Func,omitempty"` // function message
	List []*NodeInfo `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"` // node list
}

func (x *GetApiConnRsp) Reset() {
	*x = GetApiConnRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watch_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiConnRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiConnRsp) ProtoMessage() {}

func (x *GetApiConnRsp) ProtoReflect() protoreflect.Message {
	mi := &file_watch_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiConnRsp.ProtoReflect.Descriptor instead.
func (*GetApiConnRsp) Descriptor() ([]byte, []int) {
	return file_watch_proto_rawDescGZIP(), []int{9}
}

func (x *GetApiConnRsp) GetFunc() *FuncMsg {
	if x != nil {
		return x.Func
	}
	return nil
}

func (x *GetApiConnRsp) GetList() []*NodeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_watch_proto protoreflect.FileDescriptor

var file_watch_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x77, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x70, 0x75, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x43, 0x70, 0x75, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x46,
	0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x46, 0x72,
	0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x6e, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x4e, 0x75, 0x6d, 0x22, 0x44, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6b, 0x0a, 0x07,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x52, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x05, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x05, 0x46,
	0x75, 0x6e, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x41, 0x70, 0x69, 0x52, 0x05, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x22, 0x41, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x46, 0x75, 0x6e, 0x63, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x46, 0x75,
	0x6e, 0x63, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4b,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x12,
	0x1c, 0x0a, 0x04, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x46, 0x75, 0x6e, 0x63, 0x41, 0x70, 0x69, 0x52, 0x04, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x1c, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x75,
	0x6e, 0x63, 0x41, 0x70, 0x69, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4d,
	0x73, 0x67, 0x52, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x75, 0x6e, 0x63, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x46, 0x75, 0x6e, 0x63, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x70, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x75, 0x6e, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x52,
	0x04, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x1d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watch_proto_rawDescOnce sync.Once
	file_watch_proto_rawDescData = file_watch_proto_rawDesc
)

func file_watch_proto_rawDescGZIP() []byte {
	file_watch_proto_rawDescOnce.Do(func() {
		file_watch_proto_rawDescData = protoimpl.X.CompressGZIP(file_watch_proto_rawDescData)
	})
	return file_watch_proto_rawDescData
}

var file_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_watch_proto_goTypes = []interface{}{
	(*SystemStatus)(nil),  // 0: SystemStatus
	(*SendAllRsp)(nil),    // 1: SendAllRsp
	(*SendRsp)(nil),       // 2: SendRsp
	(*RegisteredRsp)(nil), // 3: RegisteredRsp
	(*GetFuncMsgReq)(nil), // 4: GetFuncMsgReq
	(*GetFuncMsgRsp)(nil), // 5: GetFuncMsgRsp
	(*GetNodeMsgReq)(nil), // 6: GetNodeMsgReq
	(*GetNodeMsgRsp)(nil), // 7: GetNodeMsgRsp
	(*GetApiConnReq)(nil), // 8: GetApiConnReq
	(*GetApiConnRsp)(nil), // 9: GetApiConnRsp
	(*NodeInfo)(nil),      // 10: NodeInfo
	(*FuncApi)(nil),       // 11: FuncApi
	(*FuncMsg)(nil),       // 12: FuncMsg
}
var file_watch_proto_depIdxs = []int32{
	2,  // 0: SendAllRsp.Result:type_name -> SendRsp
	10, // 1: RegisteredRsp.Watch:type_name -> NodeInfo
	11, // 2: RegisteredRsp.Funcs:type_name -> FuncApi
	11, // 3: GetFuncMsgRsp.Func:type_name -> FuncApi
	11, // 4: GetFuncMsgRsp.List:type_name -> FuncApi
	10, // 5: GetNodeMsgRsp.Data:type_name -> NodeInfo
	10, // 6: GetNodeMsgRsp.List:type_name -> NodeInfo
	12, // 7: GetApiConnRsp.Func:type_name -> FuncMsg
	10, // 8: GetApiConnRsp.List:type_name -> NodeInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_watch_proto_init() }
func file_watch_proto_init() {
	if File_watch_proto != nil {
		return
	}
	file_node_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_watch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAllRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFuncMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFuncMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watch_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiConnRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watch_proto_goTypes,
		DependencyIndexes: file_watch_proto_depIdxs,
		MessageInfos:      file_watch_proto_msgTypes,
	}.Build()
	File_watch_proto = out.File
	file_watch_proto_rawDesc = nil
	file_watch_proto_goTypes = nil
	file_watch_proto_depIdxs = nil
}
